### ISSUE TITLE
Uncaught TypeError: this.webview.reloadIgnoringCache is not a function

### ISSUE THREAD

**Issue by CiaranOMara** [JunoLab/language-weave#40]
[Enter steps to reproduce:]

1. Click to weave HTML document.

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.4
**Thrown From**: [language-weave](https://github.com/JunoLab/language-weave) package 0.7.0

### Stack Trace

Uncaught TypeError: this.webview.reloadIgnoringCache is not a function

```
At /Users/username/.atom/packages/language-weave/lib/html-preview.js:49

TypeError: this.webview.reloadIgnoringCache is not a function
    at HTMLPreview.reloadWebview (/packages/language-weave/lib/html-preview.js:49:26)
    at /packages/language-weave/lib/html-preview.js:38:26)
    at FSWatcher.emit (events.js:194:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
```

### Commands

```
     -0:12.2.0 weave:weave-to-html (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
ftp-remote-edit 0.18.0 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.4 
julia-client 0.12.5 
language-julia 0.19.3 
language-weave 0.7.0 
latex-completions 0.3.6 
pdf-view-plus 1.11.0 
tool-bar 1.3.0 
uber-juno 0.3.0 
```

**Comment by aviatesk** [comment]
yeah, atom@1.47.0 happened to disable webviews by default, which we use to render generate HTMLs. [The fix](https://github.com/atom/atom/pull/20741) is already in master, but the release including that hasn’t come yet. Easy workaround is to downgrade Atom to 1.46.0 or update to the coming nightly release.
